---
name: Prettier

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run:
    name: Can the code be prettier? 🤔
    runs-on: ubuntu-latest
    # workflow_dispatch always lets you select the branch ref, even though in this case we only ever want to run the action on `main` this we need an if check
    if: ${{ github.ref_name == 'main' }}
    permissions:
      contents: write # for gr2m/create-or-update-pull-request-action to push local changes
      pull-requests: write # for gr2m/create-or-update-pull-request-action to create a PR
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci --ignore-scripts --only-dev
      - uses: actions/cache@v3
        with:
          path: node_modules/.cache/prettier/.prettier-cache
          key: prettier-${{ hashFiles('package-lock.json') }}-${{ hashFiles('.gitignore') }}
      - run: npm run prettier
      - run: git restore .github/workflows
        name: Remove changes to workflow files, as it's a bad idea to let robots change their own workflow definitions
      - uses: gr2m/create-or-update-pull-request-action@df20b2c073090271599a08c55ae26e0c3522b329 # v1.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PR_TOKEN }}
        with:
          author: github-actions <41898282+github-actions[bot]@users.noreply.github.com>
          branch: actions/prettier-if-needed
          title: 'chore(prettier): fix unformatted files'
          body: A robot ran `npm run prettier` and made this PR.
          commit-message: 'chore(prettier): 🤖 ✨'
          labels: 🤖 bot
